### ISSUE TITLE
Limit maximum velocity

### ISSUE THREAD

**Issue by Jondolf** [Jondolf/avian#410]
It should be possible to set a cap on the maximum linear and angular velocities of bodies. This could be used to improve stability, prevent velocities from ever becoming infinite (although of course that shouldn't happen anyway), and to allow users to limit things like the maximum movement speed of their characters.

This should be configurable at the entity level using components:

```rust
#[derive(Component)]
pub struct MaxLinearVelocity(pub Vector);

#[cfg(feature = "2d")]
#[derive(Component)]
pub struct MaxAngularVelocity(pub Scalar);

#[cfg(feature = "3d")]
#[derive(Component)]
pub struct MaxAngularVelocity(pub Vector);
```

And ideally also at a global level using some resource. `SolverConfig` could be an option, but we could also create a new, more discoverable resource that also has configuration for things like default damping and material properties (see #119).

## Open Questions

- What resource do we put the default configuration in?
- Do we only apply the clamping before position and velocity integration, or everywhere that uses velocities? (maybe check what Box2D does here for reference)

**Comment by Oreboat** [comment]
I'm no physics expert so take my comment with a grain of salt because it may not be super good
but for the first question, I think it would be a good idea to just have it as part of the rigidbody component like LinearVelocity is, and for the second question I think it would make sense to have it everywhere that has a velocity since someone may, say, want a box to fall at a maximum of 1 meter for second for gameplay purposes
