### ISSUE TITLE
Refactor spatial query APIs to accept config over a `struct`

### ISSUE THREAD

**Issue by janhohenheim** [Jondolf/avian#442]
[Context](https://discord.com/channels/691052431525675048/1124043933886976171/1259495589737926738)

Quoting @Jondolf:

> It could just be something like
```rust
pub struct RayCastConfig {
    pub max_time_of_impact: Scalar,
    pub solid: bool,
    // We could split this I guess
    pub filter: SpatialQueryFilter,
}
```
> and people wouldn't need to worry about configuring everything manually since it'd derive `Default`. In the ideal case, spatial queries can become more concise, like

```rust
spatial.cast_ray(origin, direction, default());
```

> instead of
```rust
spatial.cast_ray(
    origin,
    direction,
    f32::MAX,
    true,
    default(),
);
```

**Comment by Jondolf** [comment]
#510 partially fixes this, in that it uses a struct for shape casts, since they have way too many niche configuration options otherwise. This approach also matches Parry and Rapier.

However, I decided not to change ray casts to use a config struct yet (especially just before the 0.2 release), since I think the filter should still be separate from the configuration, and at that point you're only storing two properties in the struct. The benefit for ray casts is less clear / in some cases the ergonomics are even slightly worse. We can reconsider it later though, especially if we add more configuration options for ray casts.
